* setup.do
* Centralized path setup for AI vs. Human analysis.

version 15.0
set more off

* Define project root
* If 0_Master.do (or the user) has already defined $project_root, keep it.
* Otherwise default to the current working directory.
* NOTE: do NOT use "confirm global" here -- it is not a valid Stata command and
* always errors, which previously wiped out the value set in 0_Master.do and left
* $project_root blank (breaking every downstream file path). Checking whether the
* macro expands to an empty string is the portable, version-safe way to do this.
if "$project_root" == "" {
    global project_root "."
}

* project_root points to the AI vs. human analysis folder.
global analysis_root "$project_root"
global output "$analysis_root/output"
global figures "$output/figures"
global human_generated_figures "$figures/human_generated_vs_ai_generated"
global ai_human_rated_figures "$figures/ai_rated_vs_human_rated"
global tables "$output/tables"
global data_root "$analysis_root/AI_vs_Human_Data"
capture mkdir "$output"
capture mkdir "$figures"
capture mkdir "$human_generated_figures"
capture mkdir "$ai_human_rated_figures"
capture mkdir "$tables"
capture mkdir "$data_root"

* Self-contained clean data for Viewpoints AI vs. human analyses.
* These are pre-cleaned INPUT datasets (not generated by this pipeline): the
* analysis do-files read them but never create them. They must already live in
* $data_root (AI_vs_Human_Data/). Provenance:
*   human_participant_clean_data.dta -- clean data from the social media warning
*       label (SMWL) human-experiment pipeline.
*   ai_persona_clean_data.dta        -- Viewpoints AI persona clean data
*       (an exact copy of data/1_clean_data.dta, retained for provenance).
global human_file "$data_root/human_participant_clean_data.dta"
global ai_file "$data_root/ai_persona_clean_data.dta"

* Fail loudly (with guidance) if an input dataset is missing, rather than letting
* a later "file not found" surface deep inside an analysis do-file. "confirm file"
* IS a valid Stata command (unlike "confirm global").
capture confirm file "$human_file"
if _rc != 0 {
    display as error "Required input dataset not found:"
    display as error "    $human_file"
    display as error "Place human_participant_clean_data.dta in $data_root and re-run."
    display as error "(If this path looks wrong, check that \$project_root is set correctly.)"
    error 601
}
capture confirm file "$ai_file"
if _rc != 0 {
    display as error "Required input dataset not found:"
    display as error "    $ai_file"
    display as error "Place ai_persona_clean_data.dta in $data_root and re-run."
    display as error "(If this path looks wrong, check that \$project_root is set correctly.)"
    error 601
}

* Backward-compatible folder globals
global human_data "$data_root"
global ai_data "$data_root"
